FROM maven:3.8.5-openjdk-17-slim as build
WORKDIR /workspace
COPY src/ /workspace/src/
COPY pom.xml /workspace/pom.xml
RUN mvn clean package -DskipTests

FROM openjdk:17-ea-slim
WORKDIR /workspace
COPY --from=build /workspace/target/nativeimage-1.0.0-SNAPSHOT-fat.jar /workspace/nativeimage-1.0.0-SNAPSHOT-fat.jar
EXPOSE 8888
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar nativeimage-1.0.0-SNAPSHOT-fat.jar"]
